// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    validation_registry
    (
        init => init
        upgrade => upgrade
        initJob => init_job
        submitProof => submit_proof
        verifyJob => verify_job
        cleanOldJobs => clean_old_jobs
        isJobVerified => is_job_verified
        getJobData => get_job_data
        setIdentityRegistryAddress => set_identity_registry_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
