// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    validation_registry
    (
        init => init
        upgrade => upgrade
        set_identity_registry_address => set_identity_registry_address
        init_job => init_job
        init_job_with_payment => init_job_with_payment
        submit_proof => submit_proof
        verify_job => verify_job
        clean_old_jobs => clean_old_jobs
        is_job_verified => is_job_verified
        get_job_data => get_job_data
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
