// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    identity_registry
    (
        init => init
        issue_token => issue_token
        register_agent => register_agent
        update_agent => update_agent
        getAgent => get_agent
        getAgentTokenId => agent_token_id
        agent_token_nonce => agent_token_nonce
    )
}

multiversx_sc_wasm_adapter::async_callback! { identity_registry }
