// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           15
// Async Callback:                       1
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    identity_registry
    (
        init => init
        upgrade => upgrade
        issueToken => issue_token
        registerAgent => register_agent
        updateAgent => update_agent
        setMetadata => set_metadata
        setServiceConfigs => set_service_configs_endpoint
        getAgentTokenId => agent_token_id
        getLastAgentNonce => agent_last_nonce
        getAgentId => agents
        getAgentDetails => agent_details
        getAgentMetadata => agent_metadata
        getAgentService => agent_service_config
        getAgent => get_agent
        getAgentOwner => get_agent_owner
        getMetadata => get_metadata
        getAgentServiceConfig => get_agent_service_config
    )
}

multiversx_sc_wasm_adapter::async_callback! { identity_registry }
