// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct IdentityRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for IdentityRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = IdentityRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        IdentityRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> IdentityRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn issue_token<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_display_name: Arg0,
        token_ticker: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("issue_token")
            .argument(&token_display_name)
            .argument(&token_ticker)
            .original_result()
    }

    pub fn register_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<OptionalValue<ManagedVec<Env::Api, MetadataEntry<Env::Api>>>>,
    >(
        self,
        name: Arg0,
        uri: Arg1,
        public_key: Arg2,
        metadata: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("register_agent")
            .argument(&name)
            .argument(&uri)
            .argument(&public_key)
            .argument(&metadata)
            .original_result()
    }

    pub fn update_agent<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<OptionalValue<ManagedVec<Env::Api, MetadataEntry<Env::Api>>>>,
    >(
        self,
        nonce: Arg0,
        new_uri: Arg1,
        new_public_key: Arg2,
        metadata: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("update_agent")
            .argument(&nonce)
            .argument(&new_uri)
            .argument(&new_public_key)
            .argument(&metadata)
            .original_result()
    }

    pub fn get_agent<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, AgentDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent")
            .argument(&nonce)
            .original_result()
    }

    pub fn agent_token_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, EsdtTokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_token_id")
            .original_result()
    }

    pub fn agent_token_nonce(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("agent_token_nonce")
            .original_result()
    }
}

#[type_abi]
#[derive(
    TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug,
)]
pub struct MetadataEntry<Api>
where
    Api: ManagedTypeApi,
{
    pub key: ManagedBuffer<Api>,
    pub value: ManagedBuffer<Api>,
}

#[type_abi]
#[derive(
    TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug,
)]
pub struct AgentDetails<Api>
where
    Api: ManagedTypeApi,
{
    pub name: ManagedBuffer<Api>,
    pub uri: ManagedBuffer<Api>,
    pub public_key: ManagedBuffer<Api>,
    pub owner: ManagedAddress<Api>,
    pub metadata: ManagedVec<Api, MetadataEntry<Api>>,
}

#[type_abi]
#[derive(
    TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug,
)]
pub struct AgentRegisteredEventData<Api>
where
    Api: ManagedTypeApi,
{
    pub name: ManagedBuffer<Api>,
    pub uri: ManagedBuffer<Api>,
}
