// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct IdentityRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for IdentityRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = IdentityRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        IdentityRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> IdentityRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn issue_token<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_display_name: Arg0,
        token_ticker: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("issue_token")
            .argument(&token_display_name)
            .argument(&token_ticker)
            .original_result()
    }

    /// Register a new agent with name, URI, public key, and optional metadata entries. 
    ///  
    /// # Arguments 
    /// * `name` - Display name of the agent 
    /// * `uri` - URI pointing to the Agent Registration File (ARF) JSON 
    /// * `public_key` - Public key for signature verification 
    /// * `metadata` - Optional list of key-value metadata entries (EIP-8004 compatible) 
    pub fn register_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<OptionalValue<ManagedVec<Env::Api, MetadataEntry<Env::Api>>>>,
    >(
        self,
        name: Arg0,
        uri: Arg1,
        public_key: Arg2,
        metadata: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("register_agent")
            .argument(&name)
            .argument(&uri)
            .argument(&public_key)
            .argument(&metadata)
            .original_result()
    }

    /// Update an agent's URI, public_key, and optionally metadata. 
    /// This follows the Transfer-Execute pattern: the owner sends the agent NFT to this endpoint. 
    /// The nonce is automatically extracted from the payment. 
    pub fn update_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<OptionalValue<ManagedVec<Env::Api, MetadataEntry<Env::Api>>>>,
    >(
        self,
        new_uri: Arg0,
        new_public_key: Arg1,
        metadata: Arg2,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("update_agent")
            .argument(&new_uri)
            .argument(&new_public_key)
            .argument(&metadata)
            .original_result()
    }

    /// Set or update specific metadata entries for an agent. 
    /// This merges with existing metadata (upsert behavior). 
    pub fn set_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedVec<Env::Api, MetadataEntry<Env::Api>>>,
    >(
        self,
        nonce: Arg0,
        entries: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("set_metadata")
            .argument(&nonce)
            .argument(&entries)
            .original_result()
    }

    /// Get a specific metadata value by key for an agent. 
    pub fn get_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        key: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_metadata")
            .argument(&nonce)
            .argument(&key)
            .original_result()
    }

    /// Get the complete payment configuration for a specific agent service in one call. 
    pub fn get_agent_service_config<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        service_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, AgentServiceConfig<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service_config")
            .argument(&nonce)
            .argument(&service_id)
            .original_result()
    }

    pub fn get_agent<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, AgentDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent")
            .argument(&nonce)
            .original_result()
    }

    pub fn get_agent_id<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_id")
            .argument(&address)
            .original_result()
    }

    pub fn agent_token_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, EsdtTokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_token_id")
            .original_result()
    }

    pub fn agent_token_nonce(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("agent_token_nonce")
            .original_result()
    }

    pub fn agent_owner<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_owner")
            .argument(&nonce)
            .original_result()
    }

    pub fn agent_service_price<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        service_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service_price")
            .argument(&nonce)
            .argument(&service_id)
            .original_result()
    }

    pub fn agent_service_payment_token<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        service_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, EgldOrEsdtTokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service_payment_token")
            .argument(&nonce)
            .argument(&service_id)
            .original_result()
    }

    pub fn agent_service_payment_nonce<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        service_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service_payment_nonce")
            .argument(&nonce)
            .argument(&service_id)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug)]
pub struct MetadataEntry<Api>
where
    Api: ManagedTypeApi,
{
    pub key: ManagedBuffer<Api>,
    pub value: ManagedBuffer<Api>,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug)]
pub struct AgentServiceConfig<Api>
where
    Api: ManagedTypeApi,
{
    pub token: EgldOrEsdtTokenIdentifier<Api>,
    pub pnonce: u64,
    pub price: BigUint<Api>,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug)]
pub struct AgentDetails<Api>
where
    Api: ManagedTypeApi,
{
    pub name: ManagedBuffer<Api>,
    pub uri: ManagedBuffer<Api>,
    pub public_key: ManagedBuffer<Api>,
    pub owner: ManagedAddress<Api>,
    pub metadata: ManagedVec<Api, MetadataEntry<Api>>,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, PartialEq, Debug)]
pub struct AgentRegisteredEventData<Api>
where
    Api: ManagedTypeApi,
{
    pub name: ManagedBuffer<Api>,
    pub uri: ManagedBuffer<Api>,
}
