// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct IdentityRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for IdentityRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = IdentityRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        IdentityRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> IdentityRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn issue_token<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_display_name: Arg0,
        token_ticker: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("issueToken")
            .argument(&token_display_name)
            .argument(&token_ticker)
            .original_result()
    }

    /// Register a new agent with name, URI, public key, optional metadata, and optional service configs. 
    pub fn register_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<MultiValueEncoded<Env::Api, common::structs::MetadataEntry<Env::Api>>>,
        Arg4: ProxyArg<MultiValueEncoded<Env::Api, common::structs::ServiceConfigInput<Env::Api>>>,
    >(
        self,
        name: Arg0,
        uri: Arg1,
        public_key: Arg2,
        metadata: Arg3,
        services: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerAgent")
            .argument(&name)
            .argument(&uri)
            .argument(&public_key)
            .argument(&metadata)
            .argument(&services)
            .original_result()
    }

    /// Update an agent's URI and/or public_key. Requires sending the agent NFT. 
    pub fn update_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<OptionalValue<MultiValueEncoded<Env::Api, common::structs::MetadataEntry<Env::Api>>>>,
        Arg5: ProxyArg<OptionalValue<MultiValueEncoded<Env::Api, common::structs::ServiceConfigInput<Env::Api>>>>,
    >(
        self,
        new_name: Arg0,
        new_uri: Arg1,
        new_public_key: Arg2,
        signature: Arg3,
        metadata: Arg4,
        services: Arg5,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("updateAgent")
            .argument(&new_name)
            .argument(&new_uri)
            .argument(&new_public_key)
            .argument(&signature)
            .argument(&metadata)
            .argument(&services)
            .original_result()
    }

    /// Set or update metadata entries for an agent. O(1) per entry via MapMapper. 
    pub fn set_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, common::structs::MetadataEntry<Env::Api>>>,
    >(
        self,
        nonce: Arg0,
        entries: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setMetadata")
            .argument(&nonce)
            .argument(&entries)
            .original_result()
    }

    /// Set or update service configurations for an agent. 
    pub fn set_service_configs_endpoint<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, common::structs::ServiceConfigInput<Env::Api>>>,
    >(
        self,
        nonce: Arg0,
        configs: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setServiceConfigs")
            .argument(&nonce)
            .argument(&configs)
            .original_result()
    }

    pub fn agent_token_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, EsdtTokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentTokenId")
            .original_result()
    }

    pub fn agent_last_nonce(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLastAgentNonce")
            .original_result()
    }

    pub fn agents(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<u64, ManagedAddress<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentId")
            .original_result()
    }

    pub fn agent_details<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, common::structs::AgentDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentDetails")
            .argument(&nonce)
            .original_result()
    }

    pub fn agent_metadata<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<ManagedBuffer<Env::Api>, ManagedBuffer<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentMetadata")
            .argument(&nonce)
            .original_result()
    }

    pub fn agent_service_config<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<u32, Payment<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentService")
            .argument(&nonce)
            .original_result()
    }

    pub fn get_agent<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, common::structs::AgentDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgent")
            .argument(&nonce)
            .original_result()
    }

    pub fn get_agent_owner<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentOwner")
            .argument(&nonce)
            .original_result()
    }

    pub fn get_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        key: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getMetadata")
            .argument(&nonce)
            .argument(&key)
            .original_result()
    }

    pub fn get_agent_service_config<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u32>,
    >(
        self,
        nonce: Arg0,
        service_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<EgldOrEsdtTokenPayment<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAgentServiceConfig")
            .argument(&nonce)
            .argument(&service_id)
            .original_result()
    }
}
