// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ValidationRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ValidationRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ValidationRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ValidationRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct ValidationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ValidationRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        identity_registry_address: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&identity_registry_address)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ValidationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ValidationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn init_job<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<OptionalValue<u32>>,
    >(
        self,
        job_id: Arg0,
        agent_nonce: Arg1,
        service_id: Arg2,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("initJob")
            .argument(&job_id)
            .argument(&agent_nonce)
            .argument(&service_id)
            .original_result()
    }

    pub fn submit_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
        proof: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("submitProof")
            .argument(&job_id)
            .argument(&proof)
            .original_result()
    }

    pub fn verify_job<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("verifyJob")
            .argument(&job_id)
            .original_result()
    }

    pub fn clean_old_jobs<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, ManagedBuffer<Env::Api>>>,
    >(
        self,
        job_ids: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("cleanOldJobs")
            .argument(&job_ids)
            .original_result()
    }

    pub fn is_job_verified<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isJobVerified")
            .argument(&job_id)
            .original_result()
    }

    pub fn get_job_data<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<common::structs::JobData<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getJobData")
            .argument(&job_id)
            .original_result()
    }

    pub fn set_identity_registry_address<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setIdentityRegistryAddress")
            .argument(&address)
            .original_result()
    }
}
