// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    reputation_registry
    (
        init => init
        upgrade => upgrade
        submitFeedback => submit_feedback
        authorizeFeedback => authorize_feedback
        appendResponse => append_response
        getReputationScore => reputation_score
        getTotalJobs => total_jobs
        getValidationContractAddress => validation_contract_address
        getIdentityContractAddress => identity_contract_address
        hasGivenFeedback => has_given_feedback
        isFeedbackAuthorized => is_feedback_authorized
        getAgentResponse => agent_response
        setIdentityContractAddress => set_identity_contract_address
        setValidationContractAddress => set_validation_contract_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
