// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    reputation_registry
    (
        init => init
        submit_feedback => submit_feedback
        authorize_feedback => authorize_feedback
        append_response => append_response
        reputation_score => reputation_score
        total_jobs => total_jobs
        validation_contract_address => validation_contract_address
        identity_contract_address => identity_contract_address
        has_given_feedback => has_given_feedback
        is_feedback_authorized => is_feedback_authorized
        agent_response => agent_response
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
